#!/bin/bash

# Usage
# ./scripts/aws_artifactor_upload <bucket s3> <artifactor>
# ./scripts/aws_artifactor_upload bookingmotor.code.deploy 7

S3_BUCKET=$1
ARTIFACTOR=$2

S3_LOCATION="s3://"$S3_BUCKET"/web/"$ARTIFACTOR

aws s3 cp $ARTIFACTOR $S3_LOCATION
