#!/bin/bash
# usage:   ./scripts/aws_codedeploy <codedeploy name> <codedeploy group> <bucket s3> <artifactor>
# example: ./scripts/aws_codedeploy bmprod-cd-backend bmprod-dg-backend bookingmotor.code.deploy 7

CD_NAME=$1
CD_GROUP=$2
S3_BUCKET=$3
ARTIFACTOR=$4
CD_DESCRIPTION="descripcion_jenkins"

REGION="us-west-2"
S3_KEY="web/"$ARTIFACTOR

CD_CODE=$(aws deploy create-deployment --application-name $CD_NAME --s3-location bucket=$S3_BUCKET,key=$S3_KEY,bundleType=zip --deployment-group-name $CD_GROUP --deployment-config-name CodeDeployDefault.OneAtATime --auto-rollback-configuration enabled=false --description $CD_DESCRIPTION |jq '.deploymentId')

echo "https://console.aws.amazon.com/codesuite/codedeploy/deployments/${CD_CODE//\"}?region=$REGION"
